name: EBAC CI

on:
  push:
    branches: [master]

  
  workflow_dispatch:


jobs:

  test:
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Cypress run
        uses: cypress-io/github-action@v2
        continue-on-error: true
        with: 
          install-command: npm install
          browser: chrome
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/reports/mochawesome-report
