name: Run API Tests and Publish Report

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Instalar todas as dependências (incluindo devDependencies)
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Garantir permissões para executar os binários locais
      - name: Garantir permissões do node_modules/.bin
        run: chmod +x ./node_modules/.bin/*

      # 5️⃣ Esperar API pública ou container estar pronto (opcional)
      # Se sua API já estiver disponível publicamente em http://localhost:3000 ou outro endpoint,
      # você pode remover este passo ou ajustar a URL.
      - name: Wait for API to be ready
        run: |
          echo "Waiting for API..."
          for i in {1..30}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "API is ready!"
              break
            fi
            sleep 2
          done

      # 6️⃣ Rodar apenas os testes de API e gerar Mochawesome report
      - name: Run API tests
        run: npm run test:report:API

      # 7️⃣ Upload do relatório como artifact
      - name: Upload API test report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-api-report
          path: mochawesome-report

      # 8️⃣ Publicar relatório no GitHub Pages
      - name: Deploy API report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: mochawesome-report
          publish_branch: gh-actions
          force_orphan: true
