name: Run Tests and Publish Report

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install wait-on
        run: npm install --save-dev wait-on

      - name: Garantir permissões do node_modules/.bin
        run: chmod +x ./node_modules/.bin/*

      # Instalar Docker Compose via GitHub Action
      - name: Setup Docker Compose
        uses: docker/setup-compose-action@v1

      # Start API via Docker Compose
      - name: Start API
        run: npm run start-api

      # Wait until API is ready
      - name: Wait for API to be ready
        run: |
          echo "Waiting for API to be ready..."
          for i in {1..30}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "API is ready!"
              break
            fi
            echo "Waiting 2 seconds..."
            sleep 2
          done

      # Run Contract tests
      - name: Run Contract tests (categoriasProvider)
        run: npm run test:categoriasProvider

      - name: Run Contract tests (others)
        run: |
          npm run test:categoriasConsumer
          npm run test:produtosProvider
          npm run test:produtosConsumer

      # Run API tests
      - name: Run API tests
        run: npm run test:API

      # Merge and generate Mochawesome report
      - name: Merge and generate Mochawesome report
        run: |
          npx mochawesome-merge mochawesome-report/*.json > mochawesome.json
          npx marge mochawesome.json --reportDir mochawesome-report

      # Upload report as artifact
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: mochawesome-report

      # Deploy report to GitHub Pages
      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: mochawesome-report
          publish_branch: gh-actions
          force_orphan: true

      # Stop API
      - name: Stop API
        run: npm run stop-api