name: Run Tests and Publish Report

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      node-modules-cache: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Garantir permissões do node_modules/.bin
        run: chmod +x ./node_modules/.bin/*

  test-api:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Run API tests
        run: npm run test:API

  test-contracts:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Run Contract tests
        run: |
          npm run test:categoriasProvider
          npm run test:categoriasConsumer
          npm run test:produtosProvider
          npm run test:produtosConsumer

  merge-report:
    runs-on: ubuntu-latest
    needs: [test-api, test-contracts]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Garantir permissões do node_modules/.bin
        run: chmod +x ./node_modules/.bin/*

      - name: Merge and generate Mochawesome report
        run: |
          npx mochawesome-merge mochawesome-report/*.json > mochawesome.json
          npx marge mochawesome.json --reportDir mochawesome-report

      - name: Upload test report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: mochawesome-report

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: mochawesome-report
          publish_branch: gh-actions
          force_orphan: true