name: Run Tests and Publish Report

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Garantir permissões do node_modules/.bin
        run: chmod +x ./node_modules/.bin/*

      # Rodar API local para testes de contrato
      - name: Run Contract tests (categoriasProvider)
        run: npx start-server-and-test "npm run start-api" http://localhost:3000 "npm run test:categoriasProvider"

      - name: Run other Contract tests
        run: |
          npx start-server-and-test "npm run start-api" http://localhost:3000 "npm run test:categoriasConsumer"
          npx start-server-and-test "npm run start-api" http://localhost:3000 "npm run test:produtosProvider"
          npx start-server-and-test "npm run start-api" http://localhost:3000 "npm run test:produtosConsumer"

      # Rodar testes de API (outros endpoints, se necessário)
      - name: Run API tests
        run: npx start-server-and-test "npm run start-api" http://localhost:3000 "npm run test:API"

      # Merge e gerar relatório final
      - name: Merge and generate Mochawesome report
        run: |
          npx mochawesome-merge mochawesome-report/*.json > mochawesome.json
          npx marge mochawesome.json --reportDir mochawesome-report

      # Upload do relatório
      - name: Upload test report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: mochawesome-report

      # Deploy para GitHub Pages
      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: mochawesome-report
          publish_branch: gh-actions
          force_orphan: true