name: Run API Tests and Publish Report

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # Se você precisa do servidor API, iniciar Docker ou servidor local
      - name: Start API (if needed)
        run: npm run start-api

      # Esperar API estar pronta
      - name: Wait for API to be ready
        run: |
          echo "Waiting for API..."
          for i in {1..30}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "API is ready!"
              break
            fi
            sleep 2
          done

      # Rodar apenas os testes de API
      - name: Run API tests
        run: npm run test:report:API

      # Upload report as artifact
      - name: Upload API test report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-api-report
          path: mochawesome-report

      # Publicar no GitHub Pages
      - name: Deploy API report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: mochawesome-report
          publish_branch: gh-actions
          force_orphan: true

      # Stop API (se tiver iniciado localmente)
      - name: Stop API
        run: npm run stop-api