name: Cypress Tests using Cypress Docker Image

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
      - name: Cypress run
        uses: cypress-io/github-action@v6
        continue-on-error: true
        with:
          install-command: npm install
          browser: chrome
          start: npm start

      - name: Deploy API report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mochawesome-report
          publish_branch: gh-pages
          force_orphan: true