name: Run Categorias Test and Publish Report

on:
  push:
    branches: ["gh-actions"]
  pull_request:

jobs:
  categorias:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Categorias Tests
        run: npm run test:categorias-ci

      - name: Merge Mochawesome JSONs
        run: npx mochawesome-merge ./mochawesome-report/*.json > ./mochawesome-report/report.json

      - name: Generate final HTML report
        run: npx marge ./mochawesome-report/report.json --reportDir ./mochawesome-report --reportFilename index.html --inlineAssets

      - name: List mochawesome-report contents
        run: ls -R ./mochawesome-report

      - name: Deploy Mochawesome report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mochawesome-report
